import { describe, expect, it } from "vitest";
import { harnessSurfaceRegistry } from "../kernel/harness/surface-registry.js";
import { cliUsageText, mainUsageCommandNames } from "./usage.js";

describe("CLI usage text", () => {
  it("documents the setup dry-run approval handoff", () => {
    const usage = cliUsageText();

    // Apply refuses without BOTH the token and the digest dry-run printed
    // (setup-command.ts), so help that shows only the digest advertises a call
    // that cannot succeed.
    expect(usage).toContain("setup [--vault <path>] [--dry-run | --yes --approval-token <token> --approved-digest <sha256:...>]");
    expect(usage).toContain("First run `setup --dry-run` to show an approval digest.");
    expect(usage).toContain("Apply only with `setup --yes --approval-token <shown-token> --approved-digest <shown-digest>`.");
    expect(usage).toContain("setup: exact approval token shown by");
    expect(usage).toContain("required with --yes and never generated by --yes.");
    // The approved public leaves, with no retired note-write or link-apply verbs.
    expect(usage).toContain("note <guide|check|audit|get>");
    expect(usage).toContain("link <suggest|check>");
    expect(usage).toContain("template <list|show|scan|check|publish|review-sources|acknowledge-source|relink-source>");
    expect(usage).not.toContain("note <create|append|update");
    expect(usage).not.toContain("link <check|suggest|apply>");
    expect(usage).not.toContain("default: Templates");
    expect(usage).not.toContain("default: Inbox");
    expect(usage).toContain("--models-default");
    expect(usage).toContain("--models-descriptor <path>");
    expect(usage).toContain("--models-no-default");
    expect(usage).not.toContain("--embedding-");
  });

  it("derives public runtime choices and main commands from harness registry", () => {
    const usage = cliUsageText();

    expect(usage).toContain("oh-my-second-brain host <install|remove|sync|status> [options]");
    expect(usage).toContain("oh-my-second-brain package <check|update> [options]");
    expect(mainUsageCommandNames()).toEqual([
      "setup",
      "template",
      "contract",
      "note",
      "link",
      "bridge",
      "search",
      "index",
      "graph",
      "host",
      "package",
      "model",
      "serve",
      "hook",
      "status",
    ]);
    for (const name of mainUsageCommandNames()) {
      expect(harnessSurfaceRegistry.cliCommands.some((command) => command.name === name)).toBe(true);
    }
    expect(usage).not.toMatch(/semantic/u);
  });
});
