import { describe, expect, it } from "vitest";
import { harnessSurfaceRegistry } from "../kernel/harness/surface-registry.js";
import { cliUsageText, mainUsageCommandNames } from "./usage.js";

describe("CLI usage text", () => {
  it("documents the setup dry-run approval handoff", () => {
    const usage = cliUsageText();

    expect(usage).toContain("setup [--vault <path>] [--template-folder <path>]");
    expect(usage).toContain("[--dry-run | --yes --approved-digest <sha256:...>]");
    expect(usage).toContain("First run `setup --dry-run` to show an approval digest.");
    expect(usage).toContain("Apply only with `setup --yes --approved-digest <shown-digest>`.");
    expect(usage).toContain("required with --yes and never generated by --yes.");
    expect(usage).toContain("--models-default");
    expect(usage).toContain("--models-descriptor <path>");
    expect(usage).toContain("--models-no-default");
    expect(usage).not.toContain("--embedding-");
  });

  it("derives public runtime choices and main commands from harness registry", () => {
    const usage = cliUsageText();

    expect(usage).toContain("oh-my-second-brain install [--vault <path>] [--runtime <auto|all|claude|codex|hermes>]");
    expect(usage).toContain("oh-my-second-brain uninstall [--runtime <all|claude|codex|hermes>]");
    expect(mainUsageCommandNames()).toEqual([
      "setup",
      "install",
      "uninstall",
      "update",
      "reconcile",
      "doctor",
      "audit",
      "lint",
      "link",
      "linkify",
      "search",
      "index",
      "doc",
      "embed",
      "serve",
      "mcp",
      "hook",
    ]);
    for (const name of mainUsageCommandNames()) {
      expect(harnessSurfaceRegistry.cliCommands.some((command) => command.name === name)).toBe(true);
    }
    expect(usage).not.toMatch(/semantic/u);
  });
});
