export type Digest = `sha256:${string}`;
export type DestinationClass = "managed-default" | "registered-existing";
export type TemplateFolderPath = string & { readonly __kind: "TemplateFolderPath" };
export type TemplateSourcePath = string & { readonly __kind: "TemplateSourcePath" };
export type TemplateId = string & { readonly __kind: "TemplateId" };
export type FieldNormalize = "lower" | "trim" | "kebab";
export type ObsidianContractType = "text" | "string" | "select" | "number" | "boolean" | "checkbox" | "date" | "datetime" | "list" | "multitext" | "multi" | "tags" | "aliases" | "file";
export type JsonValue = null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };
export type Extensions = Readonly<Record<string, JsonValue>>;
export type FieldDefault = { readonly kind: "literal"; readonly value: JsonValue } | { readonly kind: "token"; readonly token: "today" | "now" | "title" };
export interface FieldPolicy { readonly type?: ObsidianContractType; readonly required?: boolean; readonly normalize?: FieldNormalize; readonly allowedValues?: readonly string[]; readonly format?: "url"; readonly default?: FieldDefault; readonly allowTemplateDefault?: boolean; readonly immutable?: boolean; readonly intent?: string; readonly extensions?: Extensions; }
export interface BaseContract { readonly fields: Readonly<Record<string, FieldPolicy>>; readonly extensions?: Extensions; }
export interface RetrievalView { readonly name: string; readonly keys: readonly string[]; readonly extensions?: Extensions; }
export interface ContractDefinition extends BaseContract { readonly intent: string; readonly views: readonly RetrievalView[]; }
export interface TemplateBinding { readonly templateId: TemplateId; readonly destinationClass: DestinationClass; readonly sourcePath: TemplateSourcePath; readonly contract: string; readonly naming: string; readonly extensions?: Extensions; }
export interface TemplatePolicy { readonly version: 1; readonly templateFolder: TemplateFolderPath; readonly base: BaseContract; readonly contracts: Readonly<Record<string, ContractDefinition>>; readonly templates: Readonly<Record<string, TemplateBinding>>; readonly extensions?: Extensions; }
export interface GlobalAxis { readonly kind: "folder" | "link"; readonly key: string; readonly type: ObsidianContractType; readonly intent?: string; readonly members: readonly JsonValue[]; readonly extensions?: Extensions; }
export type GlobalAxes = Readonly<Record<string, GlobalAxis>>;
export interface SourceDescriptor { readonly logicalId?: string; readonly path?: string; readonly signature: Digest; readonly extensions?: Extensions; }
export interface SourceSignature { readonly algorithm: "sha256-lp-v1"; readonly inputSignature: Digest; readonly sources: readonly SourceDescriptor[]; }
export interface DerivedTemplateProjection { readonly templateId: TemplateId; readonly destinationClass: DestinationClass; readonly sourcePath: TemplateSourcePath; readonly targetFolder: TemplateFolderPath; readonly keyOrder: readonly string[]; readonly fields: Readonly<Record<string, FieldPolicy>>; readonly views: readonly RetrievalView[]; readonly naming: string; readonly bodySignature: Digest; readonly extensions?: Extensions; }
export interface DerivedProjection { readonly version: "oms.types.v1"; readonly generatedFrom: SourceSignature; readonly managed: { readonly base: BaseContract; readonly templates: Readonly<Record<string, DerivedTemplateProjection>>; readonly globalAxes: GlobalAxes; }; readonly extensions?: Extensions; }
export interface ResolvedTemplate { readonly id: TemplateId; readonly destinationClass: DestinationClass; readonly sourcePath: TemplateSourcePath; readonly targetFolder: TemplateFolderPath; readonly bom: boolean; readonly eol: "lf" | "crlf"; readonly finalNewline: boolean; readonly keyOrder: readonly string[]; readonly fields: Readonly<Record<string, FieldPolicy>>; readonly frontmatterTemplate: Readonly<Record<string, JsonValue>>; readonly body: string; readonly naming: string; readonly views: readonly RetrievalView[]; readonly inputSignature: Digest; readonly templateSignature: Digest; readonly managedSourcePaths: readonly TemplateSourcePath[]; }
export interface ResolvedConvention { readonly base: BaseContract; readonly templates: Readonly<Record<string, ResolvedTemplate>>; readonly globalAxes: GlobalAxes; readonly managedSourcePaths: readonly TemplateSourcePath[]; readonly inputSignature: Digest; }
export interface PreparedWrite { readonly mode: "create" | "append" | "update"; readonly templateId: TemplateId; readonly resolvedAt: string; readonly notePath: string; readonly frontmatter: Readonly<Record<string, JsonValue>>; readonly body: string; readonly inputSignature: Digest; readonly templateSignature: Digest; }
export type AuthorityKind = "template" | "policy" | "taxonomy" | "obsidian-types" | "legacy-contract" | "legacy-concept";
export interface AuthorityEntry { readonly kind: AuthorityKind; readonly logicalId: string; readonly vaultRelativePath: string | null; readonly contentDigest: Digest; }
export interface PlacementEntry { readonly templateId: TemplateId; readonly destinationClass: DestinationClass; readonly templateFolder: TemplateFolderPath | null; readonly sourcePath: TemplateSourcePath; }
export interface InputV2 { readonly version: 2; readonly authority: readonly AuthorityEntry[]; readonly placement: readonly PlacementEntry[]; }
export type DiagnosticCode = "TEMPLATE_ID_DUPLICATE" | "TEMPLATE_SOURCE_DUPLICATE" | "TEMPLATE_SOURCE_UNSAFE" | "TEMPLATE_SOURCE_INVALID" | "MIGRATION_OUTPUT_CONFLICT" | "MIGRATION_APPROVAL_MISMATCH" | "TEMPLATE_RECLASSIFY_PATH_MISMATCH" | "TEMPLATE_SOURCE_DRIFT" | "PROJECTION_PAYLOAD_TAMPERED" | "TEMPLATE_IDENTITY_IMMUTABLE" | "TEMPLATE_EXPRESSION_UNSUPPORTED" | "TEMPLATE_TRANSACTION_INCONSISTENT" | "MIGRATION_PUBLISHED_OUTPUT_CONFLICT" | "MIGRATION_RETRY_MISMATCH" | "TEMPLATE_TRANSACTION_MANIFEST_INVALID" | "migration-incomplete" | "BASE_CONTRACT_CONFLICT" | "TEMPLATE_POLICY_DANGLING_FIELD" | "DEFAULT_TYPE_MISMATCH" | "FORMAT_URL_INVALID" | "OBSIDIAN_TYPE_CONFLICT" | "TEMPLATE_TYPE_UNRESOLVED";
export interface Diagnostic { readonly code: DiagnosticCode; readonly templateId?: TemplateId; readonly path?: string; readonly field?: string; readonly message?: string; readonly extensions?: Extensions; }

export type TemplateMutationMode = "create" | "update" | "reclassify" | "relocate-folder";
export type LogicalOperationKind = TemplateMutationMode;
export type ControlKind = "policy" | "taxonomy" | "projection";
export type ControlPath = ".oms/template-policy.json" | ".oms/taxonomy.json" | ".oms/types.json";
export type TransactionPath = TemplateSourcePath | ControlPath;
export type TemplateTransactionMarkerPath = ".oms/template-migration.json" | ".oms/template-transaction.json" | ".oms/template-backfill.json" | ".oms/template-regenerate.json";
export type FileExpectation = { readonly state: "absent" } | { readonly state: "present"; readonly signature: Digest };
export type VerifiedFileState = { readonly state: "absent" } | { readonly state: "present"; readonly bytes: Uint8Array; readonly signature: Digest };
export interface ResolvedTemplateSourceSignatures { readonly templateId: TemplateId; readonly sourcePath: TemplateSourcePath; readonly inputSignature: Digest; readonly templateSignature: Digest; }
export interface TemplateSemanticSnapshot { readonly input: InputV2; readonly inputDigest: Digest; readonly bindings: readonly TemplateBinding[]; readonly resolvedTemplates: readonly ResolvedTemplateSourceSignatures[]; }
export interface ControlTransition<K extends ControlKind, P extends ControlPath> { readonly kind: K; readonly path: P; readonly expectedCurrent: FileExpectation; readonly current: VerifiedFileState; readonly proposed: Extract<VerifiedFileState, { readonly state: "present" }>; readonly action: "write" | "verify-only"; }
export interface SourceTransition { readonly templateId: TemplateId; readonly path: TemplateSourcePath; readonly expectedCurrent: FileExpectation; readonly current: VerifiedFileState; readonly proposed: VerifiedFileState; readonly action: "write" | "delete" | "verify-only"; }
export interface TemplateMove { readonly templateId: TemplateId; readonly strategy: "oms-managed-rename" | "register-already-moved" | "no-op"; readonly oldPath: TemplateSourcePath; readonly newPath: TemplateSourcePath; readonly sourceSignature: Digest; }
export interface LogicalOperation { readonly kind: LogicalOperationKind; readonly templateId: TemplateId; readonly destinationClass: DestinationClass; readonly payloadDigest: Digest; readonly stableRelativeSuffix: null; }
export interface PlannedPhysicalOutput { readonly finalVaultRelativePath: TransactionPath; readonly payloadDigest: Digest; }
export interface TemplateCompositionManifest { readonly version: 1; readonly mode: TemplateMutationMode; readonly current: TemplateSemanticSnapshot; readonly proposed: TemplateSemanticSnapshot; readonly controls: readonly [ControlTransition<"policy", ".oms/template-policy.json">, ControlTransition<"taxonomy", ".oms/taxonomy.json">, ControlTransition<"projection", ".oms/types.json">]; readonly sources: readonly SourceTransition[]; readonly operations: readonly LogicalOperation[]; readonly diagnostics: readonly Diagnostic[]; readonly moves: readonly TemplateMove[]; readonly outputs: readonly PlannedPhysicalOutput[]; readonly approvalDigest: Digest; readonly outputDigest: Digest; }
export interface SourceCasExpectation { readonly templateId: TemplateId; readonly path: TemplateSourcePath; readonly expected: FileExpectation; }
export interface TemplateCasExpectation { readonly input: Digest; readonly controls: Readonly<{ policy: FileExpectation; taxonomy: FileExpectation; projection: FileExpectation; }>; readonly sources: readonly SourceCasExpectation[]; }
export interface TemplateDryRunRequest { readonly dryRun: true; readonly approvedDigest?: never; }
export interface TemplateApplyRequest { readonly dryRun?: false; readonly approvedDigest: Digest; }
export type GuardedTemplateRequest = TemplateDryRunRequest | TemplateApplyRequest;
export interface SourceProposal { readonly path: TemplateSourcePath; readonly bytes: Uint8Array; readonly publication: "write" | "verify-existing"; }
export type TemplateSemanticChange = { readonly mode: "create"; readonly binding: TemplateBinding; readonly source: SourceProposal; } | { readonly mode: "update"; readonly templateId: TemplateId; readonly binding: TemplateBinding; readonly source: SourceProposal; readonly moveStrategy?: "oms-managed-rename" | "register-already-moved"; } | { readonly mode: "reclassify"; readonly templateId: TemplateId; readonly toClass: DestinationClass; } | { readonly mode: "relocate-folder"; readonly templateFolder: TemplateFolderPath; };
export interface TaxonomyControlProposal { readonly expectedCurrent: FileExpectation; readonly proposedBytes: Uint8Array; readonly action: "write" | "verify-only"; }
export interface TemplateCompositionOptions {
  readonly expected: TemplateCasExpectation;
  readonly taxonomy: TaxonomyControlProposal;
  /** Explicit doctor regeneration may replace a stale projection after all source/control CAS checks. */
  readonly allowProjectionRepair?: boolean;
}
export type TransactionVerifiedPath = { readonly path: TransactionPath; readonly state: "absent" } | { readonly path: TransactionPath; readonly state: "present"; readonly payloadDigest: Digest; };
export type TemplateTransactionReceipt = { readonly status: "planned" | "unchanged"; readonly mode: TemplateMutationMode; readonly currentInputDigest: Digest; readonly proposedInputDigest: Digest; readonly approvalDigest: Digest; readonly outputDigest: Digest; readonly operations: readonly LogicalOperation[]; readonly moves: readonly TemplateMove[]; readonly outputs: readonly PlannedPhysicalOutput[]; readonly writtenPaths: readonly []; readonly deletedPaths: readonly []; } | { readonly status: "applied" | "already-complete"; readonly mode: TemplateMutationMode; readonly transactionId: string; readonly currentInputDigest: Digest; readonly inputDigest: Digest; readonly approvedDigest: Digest; readonly outputDigest: Digest; readonly operations: readonly LogicalOperation[]; readonly moves: readonly TemplateMove[]; readonly writtenPaths: readonly TransactionPath[]; readonly deletedPaths: readonly TemplateSourcePath[]; readonly verified: readonly TransactionVerifiedPath[]; readonly markerState: "complete"; } | { readonly status: "rejected" | "inconsistent"; readonly mode: TemplateMutationMode; readonly currentInputDigest: Digest; readonly proposedInputDigest: Digest; readonly approvalDigest: Digest; readonly outputDigest: Digest; readonly diagnostics: readonly Diagnostic[]; readonly repair: readonly TransactionPath[]; };
export type MigrationMarker = { readonly status: "in-progress" | "complete"; readonly migrationId: string; readonly inputDigest: Digest; readonly approvalDigest: Digest; readonly outputDigest?: Digest; readonly checksum: Digest; readonly completedAt?: string; };
export interface MigrationReceipt { readonly status: "planned" | "applied" | "already-complete"; readonly migrationId: string; readonly inputDigest: Digest; readonly approvalDigest: Digest; readonly outputDigest?: Digest; readonly diagnostics: readonly Diagnostic[]; }
